apiVersion: v1
kind: Service
metadata:
  name: ftps
spec:
  selector:
    app: ftps
  ports:
  - name: ftps
    port: 21
    targetPort: 21
  - name: kube-ftps-one
    port: 21000
    targetPort: 21000
  - name: kube-ftps-two
    port: 21001
    targetPort: 21001
  - name: kube-ftps-three
    port: 21002
    targetPort: 21002
  - name: kube-ftps-four
    port: 21003
    targetPort: 21003
  type: LoadBalancer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftps-pv
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/var/lib/ftps"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-pv-claim
  labels:
    app: ftps
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      labels:
        app: ftps
    spec:
      volumes:
      - name: ftps-pv
        persistentVolumeClaim:
          claimName: ftps-pv-claim
      containers:
      - name: ftps
        image: ftps_alpine
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pidof telegraf
          initialDelaySeconds: 30
          periodSeconds: 2
        volumeMounts:
        - name: ftps-pv
          mountPath: /home
        imagePullPolicy: Never
        ports:
        - containerPort: 21
        - containerPort: 21000
        - containerPort: 21001
        - containerPort: 21002
        - containerPort: 21003
