apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
spec:
  type: ClusterIP
  selector:
    app: influxdb
    tier: influxdb
  ports:
  - name: influxdb
    protocol: TCP
    port: 8086

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pv-claim
  labels:
    app: influxdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
spec:
  selector:
    matchLabels:
      app: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influxdb
        tier: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb_alpine
        livenessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - pidof telegraf
          initialDelaySeconds: 30
          periodSeconds: 2
        imagePullPolicy: Never
        securityContext:
          privileged: true
        ports:
        - name: influxdb
          containerPort: 8086
        volumeMounts:
        - name: influxdb-persistent-storage
          mountPath: /var/lib/influxdb
      volumes:
        - name: influxdb-persistent-storage
          persistentVolumeClaim:
              claimName: influxdb-pv-claim
