---
apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin
    tier: phpmyadmin
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: phpmyadmin
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin_alpine
        ports:
        - containerPort: 5000
        imagePullPolicy: Never
        env:
          - name: PMA_HOST
            value: mysql
          - name: PMA_PORT
            value: "3306"
          - name: PMA_USER
            value: root
          - name: MYSQL_ROOT_PASSWORD
            value: password 