FROM alpine:latest

RUN apk add --no-cache --virtual .build-deps unzip
RUN apk add --no-cache apache2 php7 php7-apache2 php7-openssl php7-xml php7-pdo php7-mcrypt php7-session php7-mysqli php7-zlib su-exec
RUN mkdir -p /run/apache2 /run/httpd

WORKDIR /scripts

RUN wget https://wordpress.org/latest.tar.gz \
&& tar -xvf latest.tar.gz \
&& mv wordpress/* /www \
&& rm -rf /var/cache/apk/*

COPY scripts/start.sh start.sh
COPY files/wp-config.php ${APACHE_SERVER_PATH}/wp-config.php

EXPOSE 80

ENTRYPOINT [ "./start.sh" ]
